### PR TITLE
Support PayPal Express Checkout #27

### PR DESCRIPTION
**Pull request by Longkt**

### CODE REVIEW

**Comment by htdat** [comment]
1 - It seems not to work with the correct order status. Seems similar to this for PayPal standard - #37 

screen shot on 2018-04-17 at 22 17 24

2 - I expect to see something like the warning like this. 

screen shot on 2018-04-17 at 22 23 08

**Comment by Longkt** [comment]
How can it change from `on hold` to `processing`?


And the `order notes` always show `Payment pending (unilateral). Order status changed from Pending payment to On hold.`
The reason status is `unilateral` seem not an error of the code.
Looks some information on
https://www.paypal-community.com/t5/Holds-reversals-reserves/Payment-status-Payment-pending-unilateral/td-p/1340267

**Comment by Longkt** [comment]
Only Paypal Credit can be displayed on the checkout page





Is that your idea?

**Comment by Longkt** [comment]
Found a way to add exchange rate info after `Checkout with PayPal` button

**Comment by htdat** [comment]
Yes, continue to review and make sure that we can add the proper info with all of the possible places.

**Pull request merged**
